export const ALLOWED_CATEGORIES = [
  'Ahorro MENSUAL',
  'Wynwood',
  'Gastos Fijos',
  'Inversiones',
  'Gastos Sin Culpa',
  'Inflow: Ready to Assign',
  'Deferred Income SubCategory',
  'Uncategorized',
  'TC BBVA SIGNATURE',
  'TC IO',
  'TC IBK',
  'CUPON SAGA',
  'BCP TC 4910',
  'Alquiler',
  'Parrillada',
  'Seguro Vehicular',
  'Psicolo',
  'Gaseosa',
  'Familia',
  'Almuerzos Y Cenas',
  'Gas',
  'Suscripciones Mensuales',
  'Membresia gimnasio',
  'Electricidad',
  'Celular',
  'Transporte',
  'Comidas Pequeñas',
  'Cosas De La Casa',
  'Limpieza',
  'Internet',
  'Blass',
  'Gastos Del Auto',
  'AQUILARIA',
  'AQUILARIA Gastos Fijos',
  'Suscripción Trimestral NHSS',
  'Subscripción anual YNAB',
  'Ropa',
  'Regalos',
  'Medical',
  'Libros',
  'Extras',
  'Reposición De Ahorro',
  'MAZDA CX5',
  'CH SCOTIABANK',
  'Deudas',
  'Dentista',
  'Impuestos',
  'Perfumes',
  'Mazda CX5',
  'Trabajo',
  'Vitaminas',
  'Skincare',
  'Auto Reparación',
  'CTS',
  'oficina',
  'Ahorro Dolares',
  'Estudios',
  'Peluquería y relacionados',
  'Vacation',
  'Casa',
  'Emergencia',
  'Salidas',
  'Gaming',
  'Donaciones',
  'Pasatiempos',
  'Préstamo Casa',
  'Préstamo Temporal',
] as const;

export type Category = (typeof ALLOWED_CATEGORIES)[number];
