export const ALLOWED_CATEGORIES = [
  'Gastos FSCI > Ahorro MENSUAL',
  'Gastos FSCI > Wynwood',
  'Gastos FSCI > Gastos Fijos',
  'Gastos FSCI > Inversiones',
  'Gastos FSCI > Gastos Sin Culpa',
  'Internal Master Category > Inflow: Ready to Assign',
  'Internal Master Category > Deferred Income SubCategory',
  'Internal Master Category > Uncategorized',
  'Credit Card Payments > TC BBVA SIGNATURE',
  'Credit Card Payments > TC IO',
  'Credit Card Payments > TC IBK',
  'Credit Card Payments > CUPON SAGA',
  'Credit Card Payments > BCP TC 4910',
  'Immediate Obligations > Alquiler',
  'Immediate Obligations > Parrillada',
  'Immediate Obligations > Seguro Vehicular',
  'Immediate Obligations > Psicolo',
  'Immediate Obligations > Gaseosa',
  'Immediate Obligations > Familia',
  'Immediate Obligations > Almuerzos Y Cenas',
  'Immediate Obligations > Gas',
  'Immediate Obligations > Suscripciones Mensuales',
  'Immediate Obligations > Membresia gimnasio',
  'Immediate Obligations > Electricidad',
  'Immediate Obligations > Celular',
  'Immediate Obligations > Transporte',
  'Immediate Obligations > Comidas Pequeñas',
  'Immediate Obligations > Cosas De La Casa',
  'Immediate Obligations > Limpieza',
  'Immediate Obligations > Internet',
  'Immediate Obligations > Blass',
  'Immediate Obligations > Gastos Del Auto',
  'Inversiones > AQUILARIA',
  'Inversiones > AQUILARIA Gastos Fijos',
  'Suscripciones Anuales > Suscripción Trimestral NHSS',
  'Suscripciones Anuales > Subscripción anual YNAB',
  'True Expenses > Ropa',
  'True Expenses > Regalos',
  'True Expenses > Medical',
  'True Expenses > Libros',
  'True Expenses > Extras',
  'True Expenses > Reposición De Ahorro',
  'Debt Payments > MAZDA CX5',
  'Debt Payments > CH SCOTIABANK',
  'Debt Payments > Deudas',
  'Quality of Life Goals > Dentista',
  'Quality of Life Goals > Impuestos',
  'Quality of Life Goals > Perfumes',
  'Quality of Life Goals > Mazda CX5',
  'Quality of Life Goals > Trabajo',
  'Quality of Life Goals > Vitaminas',
  'Quality of Life Goals > Skincare',
  'Quality of Life Goals > Auto Reparación',
  'Quality of Life Goals > CTS',
  'Quality of Life Goals > oficina',
  'Quality of Life Goals > Ahorro Dolares',
  'Quality of Life Goals > Estudios',
  'Quality of Life Goals > Peluquería y relacionados',
  'Quality of Life Goals > Vacation',
  'Quality of Life Goals > Casa',
  'Quality of Life Goals > Emergencia',
  'Just for Fun > Salidas',
  'Just for Fun > Gaming',
  'Just for Fun > Donaciones',
  'Just for Fun > Pasatiempos',
  'Prestamos > Préstamo Casa',
  'Prestamos > Préstamo Temporal',
] as const;

export type Category = (typeof ALLOWED_CATEGORIES)[number];
